### ISSUE TITLE
Graph font is inherited from `raw` block when using `raw-dotrender-rule`

### ISSUE THREAD

**Issue by MDLC01** [Robotechnic/diagraph#1]
## Description

When creating a graph using `show: raw-dotrender-rule`, the graph inherits from the `raw` block font instead of the outer text font.

## Example

The following code uses the `render` function to render a graph, which inherits from the document font:

```typst
#set text(font: "Comic Sans MS")

#diagraph.render([```
  digraph {
      A -> B
      B -> C
  }
```].text)
```
![The graph uses the Comic Sans MS font](https://github.com/Robotechnic/diagraph/assets/57839069/16abea3e-4bd0-4c1d-aae0-d629e853a118)

The following code uses the `raw-dotrender-rule` function to render a graph, but this graph inherits from the `raw` block font instead of the document font (in this case, Comic Sans MS):

```typst
#show: diagraph.raw-dotrender-rule
#set text(font: "Comic Sans MS")

```dotrender
digraph {
    A -> B
    B -> C
}
```
![The same graph, but with a monospace font](https://github.com/Robotechnic/diagraph/assets/57839069/0878ffde-bebf-4cc8-a2e1-847208a1554b)

**Comment by MDLC01** [comment]
So I dug a bit, and I don't think there is an easy fix for this issue that will work no matter the "outside" font.

The show rule changes the layout of the `raw` element to display an SVG instead, but it is still a `raw` element, meaning the hard coded DejaVu Sans Mono font will always apply.

---

Basically, [this line in Typst's source code](https://github.com/typst/typst/blob/d7928a8ea347df89f501e5b3ecbb52402cae8edb/crates/typst-library/src/text/raw.rs#L362-L363) is equivalent to a global
```typst
#show raw: set text(font: "DejaVu Sans Mono")
```
which cannot be canceled.

**Comment by Robotechnic** [comment]
I ran into the same problem, so I decided to remove the show rule because after all the `render` and `raw-render` functions do the job. I also think that they allow us to render graphs more flexibly.
