### ISSUE TITLE
Render xlabels in typst

### ISSUE THREAD

**Issue by ayykamp** [Robotechnic/diagraph#15]
It would be nice to be able to render `xlabel` attributes in typst as well. Currently they don't render the same as normal `label`s.

Example: 
```dot
  graph {
    a [xlabel="a"]
  }
```
renders as:
![image](https://github.com/Robotechnic/diagraph/assets/32194363/b4361547-903a-4c24-9596-7db50fedb099)

**Comment by MDLC01** [comment]
Labels other than node labels are somewhat hard to override for technical reasons. While the hope is to eventually render all labels with Typst, this is not a feature that you can expect to see soon.

**Comment by Robotechnic** [comment]
Graphviz is now allowing us to render the xlabels with typst, it's done in b91ccde and will soon be added in a new version, I just need to fix some sizing issues.
