### ISSUE TITLE
Typst 0.11 support? 

### ISSUE THREAD

**Issue by drupol** [Robotechnic/diagraph#17]
Hello,

Typst 0.11 is about to be released and I currently have an issue when rendering a graph in a figure.

Here's the reproducer: https://typst.app/project/rIJIV-G0m-Kk-izRkkmVYb

Here's the result in Typst 0.10:

![image](https://github.com/Robotechnic/diagraph/assets/252042/2df28a9a-ae79-4ad8-b31f-c20ec9643b55)

Here's the result in Typst 0.11:

![image](https://github.com/Robotechnic/diagraph/assets/252042/f4b8d727-280a-41d4-8735-1834f4f48005)

**Comment by MDLC01** [comment]
I'll look into it

**Comment by MDLC01** [comment]
This was due to figure applying `align(center)`. See #18.
