### ISSUE TITLE
Generated SVG has a white background

### ISSUE THREAD

**Issue by MDLC01** [Robotechnic/diagraph#2]
I would expect the generated SVG to have a fully transparent background, but it does not.

For example:
````typst
#set page(fill: gray)

#diagraph.raw-render(width: 3cm, ```
  digraph {
    A -> B
  }
```)
````
![The graph has a white background that contrasts with the page's gray background](https://github.com/Robotechnic/diagraph/assets/57839069/d191a2e2-6350-4195-96e4-43bcd144a21b)

**Comment by Robotechnic** [comment]
Done
