### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by ondohotola** [Robotechnic/diagraph#20]
Given the following MWE

```dot
digraph G {
 {
		one [
			label = "First\nSecond",
			color = "#BF101D",
			fontcolor = "#BF101D"
		];
		two [
			label = "Third\nFourth",
			color = "#BF101D",
			fontcolor = "#BF101D"
		];
    }
    one -> two [
			color = "#BF101D",
			penwidth = 2,
		];

 }
```

I would expect the `\n' and the `fontcolor` to be evaluated like in the usual `dot` command.

Other than that, awesome!

**Comment by MDLC01** [comment]
The `fontcolor` issue is known and being worked on by @Robotechnic.

Regarding the `\n` issue, I will try to fix it myself.

**Comment by ondohotola** [comment]
Great, no rush :-)-O

**Comment by Robotechnic** [comment]
Done in f40906c095fc5d486be52d5007e944384856dcc0. It took some time because I reworked the protocol so it's easier to work with. I am just fixing some bugs and adding support for font size and the new version should be released soon.
