### ISSUE TITLE
[README]: Include picture preview of the code.

### ISSUE THREAD

**Issue by cybercoder-naj** [Robotechnic/diagraph#24]
I want to immediately see the result of the code written in the readme file. This would motivate others to know what they get without spending time trying it out themselves.

**Comment by MDLC01** [comment]
Furthermore, a separate README should be created for the published package (different from the GitHub repo's README), that does not include compilation instructions.

**Comment by Robotechnic** [comment]
Done.

And btw, I don't really mind but I found @cybercoder-naj's pr a little bit rude, you could have used other wording than "I want to".

**Comment by cybercoder-naj** [comment]
Apologies if I sounded rude; I didn't mean to. I was in a hurry to write a pdf which may have resulted in a poorly written issue comment. Allow me to rephrase:

# Problem

Upon reading the Readme, it is not immediate what the preview of the written examples. One has to experiment with the example code to check the corresponding output 

# Proposed changes

I believe adding a screenshot next to the example code would indicate the output I expect and judge if the library is right for me on my usecase.

---

I hope this is a better way to phrase my issue; thanks for pointing it out earlier.
