### ISSUE TITLE
Support for automatic handling of unlabeled nodes?

### ISSUE THREAD

**Issue by behackl** [Robotechnic/diagraph#27]
For an example like

```typ
#import "@preview/diagraph:0.2.4": *

#raw-render(```dot
  graph {
    node[shape=point];
    a -- b -- c -- d;
    b -- d -- a -- a;
  }
 ```)
```

where the nodes have shapes that don't print the label (not sure whether `point` is the only one in that regard), the Typst-rendered labels should also not be shown. (In case this is difficult to implement, something like passing `none` to the renderer to disable rendering the labels would be nice.) Current output:

<img width="170" alt="image" src="https://github.com/Robotechnic/diagraph/assets/11851593/69df5776-aa1e-467c-9f3c-6a936f39795a">

I've found that as a workaround, passing `labels: (: a: "", b: "", c: "", d: "")` works, but this is slightly annoying for large graphs.

Sorry in case I've missed something that enables the correct behavior already -- and thanks for the useful plugin! 🚀

**Comment by MDLC01** [comment]
You are right that the labels should not be displayed by default for such node shapes. I also agree passing `none` as a label should act like passing `""`.

**Comment by behackl** [comment]
Just to be explicit, what I meant with my suggestion concerning `none` was that passing `none` instead of the dictionary, i.e.,`labels: none` (with this acting as if `""` was specified for every individual node) would have been useful to me. :-)

I'm not sure whether there is still a usecase for this if the absence of labels given particular node shapes is dealt with correctly though.
