### ISSUE TITLE
How to do equations on the edges?

### ISSUE THREAD

**Issue by Kreijstal** [Robotechnic/diagraph#28]
You can do it on the nodes, but I can't figure out how to do it on the edges..

**Comment by Robotechnic** [comment]
Until the last version of graphviz it wasn't possible to do so. It is possible now but I haven't implemented it yet, I'm searching for a way to conveniently express which edge label to override because it is possible to add multiple edges between two nodes.

**Comment by Robotechnic** [comment]
It wasn't so complicated after all. It is now possible with the version 0.3.0.
