### ISSUE TITLE
Use an external .dot file ?

### ISSUE THREAD

**Issue by drupol** [Robotechnic/diagraph#3]
Hi,

I'm using this package for Typst, thank you for it :)

I was wondering if it would be possible to use an external file as input to the graph?

Thank you!

**Comment by Robotechnic** [comment]
Yes,
It is currently possible:
```typ
#raw-render(read("someFile.dot"),...)
```
But as it is convenient I may add a `dot-render` function to render a file directly.

**Comment by drupol** [comment]
Oh nice ! Thanks :)

**Comment by drupol** [comment]
Worked perfectly !

![image](https://github.com/Robotechnic/diagraph/assets/252042/cf0eb815-6a54-48e9-a1d9-71e7f8fd2a6f)
