### ISSUE TITLE
Failed to download package (Error: not found) 

### ISSUE THREAD

**Issue by joyboy67** [Robotechnic/diagraph#35]
Hello, I added this `#import "@preview/diagraph:0.3.1": *` to my typst file in the typst web app but I get :  

`Failed to download package (Error: not found) (line 3)`

**Comment by joyboy67** [comment]
> Hello, I added this `#import "@preview/diagraph:0.3.1": *` to my typst file in the typst web app but I get :
> 
> `Failed to download package (Error: not found) (line 3)`

**Comment by Robotechnic** [comment]
Hello, I didn't have enough time to test my changes properly before submitting the package so I didn't submitted it. Sorry, I pushed the new version too early on the main. Until then, use the previous version.

**Comment by joyboy67** [comment]
Ok no problem ;) thank you for your work :)

**Comment by joyboy67** [comment]
Ok no problem ;) thank you for your work :)
