### ISSUE TITLE
Undirected edges not supported

### ISSUE THREAD

**Issue by mofeing** [Robotechnic/diagraph#4]
Whenever I try to draw undirected edges, `diagraph` prints a error message.

```typst
#import "@preview/diagraph:0.1.0": *
#render("digraph { a -- b; }")
```

![Captura de pantalla 2023-10-23 a las 10 27 37](https://github.com/Robotechnic/diagraph/assets/15837247/4807d978-bbcd-4ffe-b43b-36accf53f51e)

**Comment by Robotechnic** [comment]
It's because `digraph` stands for directed graph hence, you can only use a directed edge inside `->`. What you want is an undirected graph `graph` which allows `--` to denote an undirected edge.

In your case,
```typ
#import "@preview/diagraph:0.1.0": *
#render("graph { a -- b; }")
```

**Comment by mofeing** [comment]
:facepalm: you're right
I was looking for mixing directed and undirected edges inside a graph, which apparently is solved using the `[dir=none]`.
