### ISSUE TITLE
Override labels in [label=x] syntax

### ISSUE THREAD

**Issue by Goldmensch** [Robotechnic/diagraph#9]
Hi, when I try to override the labels used in `[label=x]` it just uses the string values specified behind `label=`:

````typst
raw-render(
  ```
  digraph {
    rankdir=LR;
    size="8,5"

    node [shape=circle]
    s_1 -> s_2 [label=a]
    s_1 -> s_1 [label=b]
    s_2 -> s_1 [label=b]
    s_2 -> s_2 [label=a]
  }
  ```,
  labels: (
    s_1: $s_1$,
    s_2: $s_2$,
    a: $a$,
    b: $b$
  )
)
````
![image](https://github.com/Robotechnic/diagraph/assets/47005420/3d421e22-ee27-4927-b5ab-66d2db6e958d)

This looks like a bug to me or is there any other way to do this?

**Comment by Robotechnic** [comment]
It's not a bug. Graphviz in its current state doesn't allow us to use the method we use for the node labels in edge labels. It's inconvenient but unfortunately we didn't find a reliable solution. Maybe in future version it will be possible but not now.

**Comment by Goldmensch** [comment]
Ah, that's unfortunate.
